name: Deploy Frontend to Cloudflare

on:
  push:
    branches:
      - main # or your default branch

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install Dependencies
        run: |
          cd react  # navigate to your frontend directory
          npm install

      - name: Build
        run: |
          npm run build  # build your project

      - name: Deploy to Cloudflare
        uses: cloudflare/wrangler-action@1.3.0
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          environment: "production" # or your specific environment
